---
name: SurvivalUtils
version: 1.4-dev
main: de.timmyrs.SurvivalUtils
author: timmyRS
website: https://timmyrs.de

commands:
  survivalutils: {}
  trade:
    permission: survivalutils.trade
  tpa:
    permission: survivalutils.tpa
  tpahere:
    permission: survivalutils.tpa
  tpaccept:
    permission: survivalutils.tpa
  tpcancel:
    permission: survivalutils.tpa
  warp:
    permission: survivalutils.warp
  warps:
    permission: survivalutils.warp
  setwarp:
    permission: survivalutils.setwarp
  delwarp:
    permission: sruvivalutils.delwarp
  home:
    permission: survivalutils.home
  homes:
    permission: survivalutils.home
  sethome:
    permission: survivalutils.home
  delhome:
    permission: survivalutils.home
