---
name: SurvivalUtils
version: 1.7
main: de.timmyrs.SurvivalUtils
author: timmyRS
website: https://www.spigotmc.org/resources/survivalutils.62574/

commands:
  survivalutils: {}
  tpa:
    permission: survivalutils.tpa.tpa
  tpahere:
    permission: survivalutils.tpa.tpahere
  tpaccept:
    aliases: [tpaaccept]
    permission: survivalutils.tpa.accept
  tpcancel:
    aliases: [tpacancel]
    permission: survivalutils.tpa.cancel
  tptoggle:
    aliases: [tpatoggle]
    permission: survivalutils.tpa.toggle
  warp:
    permission: survivalutils.warp
  warps:
    permission: survivalutils.warp
  setwarp:
    permission: survivalutils.managewarps
  delwarp:
    permission: survivalutils.managewarps
  home:
    permission: survivalutils.home
  homes:
    permission: survivalutils.home
  sethome:
    permission: survivalutils.home
  delhome:
    permission: survivalutils.home

permissions:
  survivalutils.tpa:
    children:
      survivalutils.tpa.tpa: true
      survivalutils.tpa.tpahere: true
      survivalutils.tpa.accept: true
  survivalutils.tpa.*:
    children:
      survivalutils.tpa: true
      survivalutils.tpa.cancel: true
      survivalutils.tpa.toggle: true
  survivalutils.warps.*:
    children:
    survivalutils.warps: true
