---
name: SurvivalUtils
version: 1.2
main: de.timmyrs.SurvivalUtils
author: timmyRS
website: https://timmyrs.de

commands:
  tpa:
    permission: survivalutils.tpa
    usage: /tpa <player>
  tpahere:
    permission: survivalutils.tpa
    usage: /tpa <player>
  tpaccept:
    usage: /tpaccept <player>
  tpcancel:
    permission: survivalutils.tpa
  warp:
    permission: survivalutils.warp
  warps:
    aliases: [warplist]
    permission: survivalutils.warp
  setwarp:
    permission: survivalutils.setwarp
  reloadsurvivalutils:
    permission: survivalutils.reload

permissions:
  survivalutils.tpa:
    default: false
  survivalutils.warp:
    default: false
  survivalutils.setwarp:
    default: false
  survivalutils.reload:
    default: false
