---
name: SurvivalUtils
version: 1.4
main: de.timmyrs.SurvivalUtils
author: timmyRS
website: https://timmyrs.de

commands:
  survivalutils: {}
  # trade:
  #   permission: survivalutils.trade
  tpa:
    permission: survivalutils.tpa.tpa
  tpahere:
    permission: survivalutils.tpa.tpahere
  tpaccept:
    aliases: [tpaaccept]
    permission: survivalutils.tpa.tpaccept
  tpcancel:
    aliases: [tpacancel]
    permission: survivalutils.tpa.tpcancel
  warp:
    permission: survivalutils.warp
  warps:
    permission: survivalutils.warp
  setwarp:
    permission: survivalutils.managewarps
  delwarp:
    permission: survivalutils.managewarps
  home:
    permission: survivalutils.home
  homes:
    permission: survivalutils.home
  sethome:
    permission: survivalutils.home
  delhome:
    permission: survivalutils.home

permissions:
  survivalutils.tpa:
    children:
      survivalutils.tpa.*: true
  survivalutils.tpa.*:
    children:
      survivalutils.tpa.tpa: true
      survivalutils.tpa.tpahere: true
      survivalutils.tpa.tpaccept: true
      survivalutils.tpa.tpcancel: true
